# Generated by Django 4.1.5 on 2023-01-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('books', models.ManyToManyField(related_name='authors', to='catalog.book')),
            ],
        ),
    ]
